os:
  - linux
  - osx
language: node_js
node_js:
  - '8'
  - '10'
  - '12'
before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export export CXX=g++-6; fi'
  - git clone -b build-windows --single-branch https://github.com/Apollon77/libmbus.git libmbus && cp config.h libmbus/config.h
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ./cc-test-reporter; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./cc-test-reporter before-build; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install socat; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install vcbuildtools; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then npm config set msvs_version 2015 --global; fi'
install:
  - npm install --debug
after_success:
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -r 22e3e060ccffa9ceda43fcdcca5445251fe4f93cf4a98547a76f7897a6b1b877; fi'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - socat
