version: 'test-{build}'
environment:
  matrix:
    - nodejs_version: '4'
    - nodejs_version: '6'
    - nodejs_version: '8'
matrix:
  allow_failures:
    - nodejs_version: '4'
    - nodejs_version: '6'
    - nodejs_version: '8'
platform:
  - x86
  - x64
clone_folder: 'c:\projects\%APPVEYOR_PROJECT_NAME%'
install:
  - ps: 'Install-Product node $env:nodejs_version $env:platform'
  - git clone -b build-windows --single-branch https://github.com/Apollon77/libmbus.git libmbus
  - cp config.h libmbus/config.h
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
build: 'off'
